export const LOAD_POSTS_SUCCESS = "LOAD_POSTS_SUCCESS";
export const LOAD_ONE_POST_SUCCESS = "LOAD_ONE_POST_SUCCESS";
export const CLEAN_ONE_POST_SUCCESS = "CLEAN_ONE_POST_SUCCESS";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const LOAD_LENGTH_SUCCESS = "LOAD_LENGTH_SUCCESS";

export const LOAD_SESSION = "LOAD_SESSION";
export const AUTHENTICATE_USER = "REQUEST_AUTHENTICATE_USER";
export const PROCESSING_AUTHENTICATE_USER = "PROCESSING_AUTHENTICATE_USER";
export const CONTINUE_AUTHENTICATE_USER = "CONTINUE_AUTHENTICATE_USER";
export const AUTHENTICATING = "AUTHENTICATING";
export const AUTHENTICATED = "AUTHENTICATED";
export const NOT_AUTHENTICATED = "NOT_AUTHENTICATED";
export const SET_STATE = "SET_STATE";
export const ADD_POST = "ADD_POST";
export const EDIT_POST = "EDIT_POST";
export const DELETE_POST = "DELETE_POST";
export const UPDATE = "UPDATE";
export const GET_POST = "GET_POST";
export const CLEAR_POSTS = "CLEAR_POSTS";

export const CREATE_USER = "CREATE_USER";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";
export const GET_USER = "GET_USER";

export const EDIT_USER = "EDIT_USER";
export const LOAD_USER_POSTS_SUCCESS = "LOAD_USER_POSTS_SUCCESS";
export const LOAD_USER_POSTS_FAILED = "LOAD_USER_POSTS_FAILED";
export const SEARCH_POSTS_SUCCESS = "SEARCH_POSTS_SUCCESS";

export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";

export const UPDATE_FEATURES = "UPDATE_FEATURES";

export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT";
